# Move base
controller_frequency: 10.0
controller_patience: 1.0

planner_frequency: 10.0
planner_patience: 5.0

oscillation_timeout: 0.0
oscillation_distance: 0.2

# Local planner
DWAPlannerROS:

# Robot Configuration Parameters
  max_vel_x: 2
  min_vel_x: -0.5

  max_vel_y: 0.0
  min_vel_y: 0.0

# The velocity when robot is moving in a straight line
  max_vel_trans:  0.26
  min_vel_trans:  0.13

  max_vel_theta: 0.8
  min_vel_theta: 0.2

  acc_lim_x: 2.5
  acc_lim_y: 0.0
  acc_lim_theta: 2
  # max_rot_vel: 
  # min_rot_vel:
# Goal Tolerance Parameters
  latch_xy_goal_tolerance: false

# Forward Simulation Parameters
  xy_goal_tolerance: 0.3
  yaw_goal_tolerance: 0.5

  # Forward Simulation Parameters
  sim_time: 1.2
  vx_samples: 30
  vy_samples: 0
  vth_samples: 40
  # ! Forward Simulation Parameters Base local
  angular_sim_granularity: 0.17

  # Trajectory Scoring Parameters
  path_distance_bias: 32.0
  goal_distance_bias: 20.0
  occdist_scale: 0.02
  forward_point_distance: 0.325
  stop_time_buffer: 0.2
  scaling_speed: 0.25
  max_scaling_factor: 0.2

  # Oscillation Prevention Parameters
  oscillation_reset_dist: 0.05
